/** Static parse helpers for legacy SOP markdown headers */
export const SECTION_HEADER_MAP: Record<string, string> = {
  purpose: 'purpose',
  scope: 'scope',
  'ministry structure': 'structure',
  structure: 'structure',
  'membership requirements': 'membership',
  membership: 'membership',
  'ministry meetings': 'meetings',
  meetings: 'meetings',
  'when to use': 'whenToUse',
  'who is responsible': 'responsible',
  "who's responsible": 'responsible',
  'before you start': 'before',
  before: 'before',
  'step-by-step procedure': 'steps',
  procedure: 'steps',
  steps: 'steps',
  'after / follow-up': 'after',
  after: 'after',
  'follow-up': 'after',
  'safety & compliance': 'safety',
  safety: 'safety',
  'contacts & escalation': 'contacts',
  contacts: 'contacts',
  escalation: 'contacts',
};
