-- AlterTable
ALTER TABLE "BandMusician" ADD COLUMN "playerType" TEXT NOT NULL DEFAULT 'regular';
ALTER TABLE "BandMusician" ADD COLUMN "guestServiceDate" TEXT;
ALTER TABLE "BandMusician" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "BandMusician" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
