import type { CueLine, MeetingSegment, SpeechCue, TimingPreset } from './club-climate-cue.types';

export const DEFAULT_TIMING_PRESET_ID = 'off' as const;

export const FONT_SCALE_MIN = 0.85;
export const FONT_SCALE_MAX = 1.8;
export const FONT_SCALE_STEP = 0.1;
export const DEFAULT_FONT_SCALE = 1.1;

export const SCROLL_SPEED_MIN = 8;
export const SCROLL_SPEED_MAX = 72;
export const SCROLL_SPEED_STEP = 4;
export const DEFAULT_SCROLL_SPEED = 24;

export const TIMING_PRESETS: readonly TimingPreset[] = [
  {
    id: 'off',
    label: 'Clock only',
    greenSeconds: 0,
    yellowSeconds: 0,
    redSeconds: 0,
    lights: false,
  },
  {
    id: '1-2',
    label: '1–2 min',
    greenSeconds: 60,
    yellowSeconds: 90,
    redSeconds: 2 * 60,
    lights: true,
  },
  {
    id: '2-3',
    label: '2–3 min',
    greenSeconds: 2 * 60,
    yellowSeconds: 150,
    redSeconds: 3 * 60,
    lights: true,
  },
  {
    id: '5-7',
    label: '5–7 min',
    greenSeconds: 5 * 60,
    yellowSeconds: 6 * 60,
    redSeconds: 7 * 60,
    lights: true,
  },
  {
    id: '8-10',
    label: '8–10 min',
    greenSeconds: 8 * 60,
    yellowSeconds: 9 * 60,
    redSeconds: 10 * 60,
    lights: true,
  },
  {
    id: '10-15',
    label: '10–15 min',
    greenSeconds: 10 * 60,
    yellowSeconds: 13 * 60,
    redSeconds: 15 * 60,
    lights: true,
  },
];

export const SPEECH_TITLE = 'Creating the Best Club Climate';
export const SPEECH_SERIES = 'The Successful Club Series';
export const SPEECH_THEME = 'National Wellness Communication for Change';
export const WORD_OF_THE_DAY = 'THRIVE';

export const SPEECH_CUES: SpeechCue[] = [
  {
    id: 'title',
    slide: 1,
    section: 'Title',
    lines: [
      { type: 'stage', text: 'SLIDE 1 — TITLE' },
      { type: 'strong', text: 'The Successful Club Series: Creating the Best Club Climate' },
      { type: 'body', text: 'Theme: **National Wellness Communication for Change.**' },
      { type: 'body', text: 'Word of the Day: **THRIVE**' },
      { type: 'stage', text: 'Begin speaking' },
    ],
  },
  {
    id: 'opening',
    slide: 1,
    section: 'Opening',
    lines: [
      { type: 'body', text: 'Good evening, Toastmasters, fellow leaders, and honored guests.' },
      { type: 'body', text: 'Our theme tonight is:' },
      { type: 'strong', text: '“National Wellness Communication for Change.”' },
      { type: 'body', text: 'And our Word of the Day is **THRIVE**.' },
    ],
  },
  {
    id: 'story-wellness-era',
    slide: 1,
    section: 'I was going to thrive',
    lines: [
      { type: 'body', text: 'A few months ago, I decided I was going to get serious about wellness.' },
      { type: 'body', text: 'I bought the water bottle. The big one. The one that makes it look like you’re training for a hike even if you’re just going to the mailbox.' },
      { type: 'body', text: 'I downloaded the app. I set the alarm. I even bought vitamins that promised I would **THRIVE**.' },
      { type: 'body', text: 'The bottle sat on my desk like a trophy. The app sent me reminders. And I drank coffee.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'story-plant',
    slide: 1,
    section: 'How is your environment?',
    lines: [
      { type: 'body', text: 'Then the app asked me a question I was not prepared for.' },
      { type: 'body', text: 'It didn’t ask how many steps I had. It asked:' },
      { type: 'quote', text: 'How is your environment?' },
      { type: 'body', text: 'I looked around my living room. I had a plant.' },
      { type: 'body', text: 'I thought, “We’re good. The plant is still alive. That’s basically thriving.”' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'story-shut-down',
    slide: 1,
    section: 'My idea got shut down',
    lines: [
      { type: 'body', text: 'Then I went to a meeting. The agenda was perfect. The room was organized. And the climate… was not.' },
      { type: 'body', text: 'I offered an idea. I thought it was a good one. I had actually thought about it before I opened my mouth.' },
      { type: 'body', text: 'And the first response was:' },
      { type: 'quote', text: 'That’s not how we normally do things.' },
      { type: 'body', text: 'I didn’t argue. I didn’t explain. I just sat there and shrank about two inches in my chair.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'story-plant-better',
    slide: 1,
    section: 'The plant was doing better than I was',
    lines: [
      { type: 'body', text: 'And I realized something.' },
      { type: 'body', text: 'I could drink all the water in that bottle. I could get eight hours of sleep. I could eat the salad.' },
      { type: 'body', text: 'But if I spend my time in a room where I don’t feel safe to speak…' },
      { type: 'body', text: 'that plant on my desk is doing better than I am.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'wellness-more',
    slide: 1,
    section: 'More than the body',
    lines: [
      { type: 'body', text: 'Because wellness isn’t just about what happens to our bodies.' },
      { type: 'bullet', text: 'There is emotional wellness.' },
      { type: 'bullet', text: 'There is mental wellness.' },
      { type: 'bullet', text: 'There is relational wellness.' },
      { type: 'body', text: 'And there is something else we don’t always think about:' },
      { type: 'strong', text: 'organizational wellness.' },
    ],
  },
  {
    id: 'environment',
    slide: 1,
    section: 'You may need a new environment',
    lines: [
      { type: 'body', text: 'Because where we spend our time affects us.' },
      { type: 'body', text: 'The people we interact with affect us.' },
      { type: 'body', text: 'And the environment we create for one another affects us.' },
      { type: 'body', text: 'You can eat healthy. Exercise every morning. Drink your water. Get eight hours of sleep.' },
      { type: 'body', text: 'But if you spend your entire day around negativity, criticism, and people who make you feel like you’re never good enough…' },
      { type: 'body', text: 'you may need more than a multivitamin.' },
      { type: 'strong', text: 'You may need a new environment!' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'thesis',
    slide: 1,
    section: 'The goal is to THRIVE',
    lines: [
      { type: 'body', text: 'And that’s what we’re talking about tonight:' },
      { type: 'strong', text: 'Creating the Best Club Climate.' },
      { type: 'body', text: 'Because the goal isn’t simply to have a club where people show up.' },
      { type: 'body', text: 'The goal is to create a club where people **THRIVE**.' },
      { type: 'body', text: 'And tonight we’re going to look at five things each of us can do to help create that kind of environment.' },
    ],
  },
  {
    id: 'slide-2',
    slide: 2,
    section: 'Club climate is the deciding factor',
    lines: [
      { type: 'stage', text: 'ADVANCE TO SLIDE 2' },
      { type: 'strong', text: 'Club Climate — The Deciding Factor' },
      { type: 'body', text: 'The first thing we need to understand is that **club climate is a deciding factor.**' },
      { type: 'body', text: 'Your PowerPoint identifies two important elements:' },
      { type: 'bullet', text: 'the learning environment' },
      { type: 'bullet', text: 'member interactions' },
    ],
  },
  {
    id: 'between-agenda',
    slide: 2,
    section: 'Between the agenda items',
    lines: [
      { type: 'body', text: 'And those two things tell us something important.' },
      { type: 'body', text: 'A successful club isn’t just about what happens on the agenda.' },
      { type: 'body', text: 'It’s also about what happens **between the agenda items.**' },
      { type: 'bullet', text: 'How we talk to one another.' },
      { type: 'bullet', text: 'How we welcome one another.' },
      { type: 'bullet', text: 'How we respond when somebody has an idea.' },
      { type: 'bullet', text: 'How we respond when somebody makes a mistake.' },
      { type: 'bullet', text: 'How we respond when somebody needs help.' },
    ],
  },
  {
    id: 'something-missing',
    slide: 2,
    section: 'Something is missing',
    lines: [
      { type: 'body', text: 'Because you can have an excellent educational program… but if people don’t feel comfortable participating, something is missing.' },
      { type: 'body', text: 'You can have great speakers… but if members are afraid to speak up, something is missing.' },
      { type: 'body', text: 'You can have a perfectly organized agenda… but if people don’t feel like they belong, something is missing.' },
      { type: 'body', text: 'So creating the best climate begins with understanding that **every interaction contributes to the environment.**' },
    ],
  },
  {
    id: 'two-leaders',
    slide: 2,
    section: 'Same suggestion, different climate',
    lines: [
      { type: 'body', text: 'Remember that meeting I told you about? That was me. That was my idea. And that was leader number one:' },
      { type: 'quote', text: 'That’s not how we normally do things.' },
      { type: 'body', text: 'Now imagine leader number two says:' },
      { type: 'quote', text: 'That’s an interesting idea. Let’s talk about how we might make that work.' },
      { type: 'body', text: 'Same suggestion. Same organization. Same person sitting in the chair. But completely different climate.' },
      { type: 'body', text: 'The first response closes the door. The second response opens one. That’s why communication matters.' },
    ],
  },
  {
    id: 'healthy-disagree',
    slide: 2,
    section: 'Disagree without disrespect',
    lines: [
      { type: 'body', text: 'And creating the best climate doesn’t mean everybody has to agree.' },
      { type: 'body', text: 'A healthy club isn’t one where everyone agrees all the time. Because if everybody agrees with everything… we probably don’t need a meeting.' },
      { type: 'body', text: 'We just need somebody to send out the minutes!' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      { type: 'body', text: 'Healthy clubs allow people to disagree respectfully.' },
      { type: 'body', text: 'We can say “I don’t agree” without saying “Therefore, I don’t respect you.”' },
      { type: 'bullet', text: 'Challenge an idea without attacking the person.' },
      { type: 'bullet', text: 'Correct someone without embarrassing them.' },
      { type: 'bullet', text: 'Have difficult conversations while still treating people with dignity.' },
      { type: 'body', text: 'That’s the climate we want to create.' },
    ],
  },
  {
    id: 'slide-3',
    slide: 3,
    section: 'Set an example',
    lines: [
      { type: 'stage', text: 'ADVANCE TO SLIDE 3' },
      { type: 'strong', text: 'Set an Example' },
      { type: 'body', text: 'The PowerPoint gives us four specific ways to do that:' },
      { type: 'bullet', text: 'Arrive prepared.' },
      { type: 'bullet', text: 'Offer assistance.' },
      { type: 'bullet', text: 'Volunteer.' },
      { type: 'bullet', text: 'Support others.' },
      { type: 'body', text: 'And this is where leadership becomes personal. Leadership isn’t simply about the title next to your name. It’s about behavior.' },
    ],
  },
  {
    id: 'model-it',
    slide: 3,
    section: 'People watch what leaders do',
    lines: [
      { type: 'body', text: 'If I expect members to arrive prepared… I have to arrive prepared.' },
      { type: 'body', text: 'If I want people to volunteer… I need to volunteer.' },
      { type: 'body', text: 'If I want people to support one another… I have to support them.' },
      { type: 'body', text: 'And if I want people to take the club seriously… I have to take the club seriously.' },
      { type: 'body', text: 'You cannot tell people what to do while consistently demonstrating the opposite.' },
      { type: 'strong', text: 'People watch what leaders do much more carefully than they listen to what leaders say.' },
    ],
  },
  {
    id: 'every-member',
    slide: 3,
    section: 'You don’t need a title',
    lines: [
      { type: 'body', text: 'And this applies to every member—not just the officers. You don’t have to be President to set an example.' },
      { type: 'bullet', text: 'Be the person who arrives early.' },
      { type: 'bullet', text: 'Help set up the room.' },
      { type: 'bullet', text: 'Volunteer for a role that nobody wants.' },
      { type: 'body', text: 'Although… if you volunteer for Timer three meetings in a row, we might start wondering what’s going on.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'contagious',
    slide: 3,
    section: 'Leadership is contagious',
    lines: [
      { type: 'body', text: 'But seriously, every time we step forward, we’re sending a message. We’re saying: **“I’m invested in this club.”**' },
      { type: 'body', text: 'And when people see that investment, it creates momentum.' },
      { type: 'bullet', text: 'One person volunteers. Then another person says, “I can help too.”' },
      { type: 'bullet', text: 'One person offers assistance. Another person realizes, “I should probably help.”' },
      { type: 'bullet', text: 'One person encourages somebody. Another person begins doing the same.' },
      { type: 'strong', text: 'Leadership is contagious.' },
      { type: 'body', text: 'When people see that behavior modeled consistently, it creates an environment where people can **THRIVE**.' },
    ],
  },
  {
    id: 'slide-4',
    slide: 4,
    section: 'Welcome guests',
    lines: [
      { type: 'stage', text: 'ADVANCE TO SLIDE 4' },
      { type: 'strong', text: 'Welcome Guests — First Impressions Count' },
      { type: 'body', text: 'Now let’s talk about people who haven’t joined us yet. The PowerPoint gives us five simple actions:' },
      { type: 'bullet', text: 'Greet guests.' },
      { type: 'bullet', text: 'Engage them in conversation.' },
      { type: 'bullet', text: 'Answer questions.' },
      { type: 'bullet', text: 'Befriend them.' },
      { type: 'bullet', text: 'Invite them to another meeting or to join.' },
    ],
  },
  {
    id: 'five-meanings',
    slide: 4,
    section: 'What those five things say',
    lines: [
      { type: 'body', text: 'Think about how powerful those five things are.' },
      { type: 'bullet', text: 'Greet them. That says: **“We see you.”**' },
      { type: 'bullet', text: 'Engage them. That says: **“We want to know you.”**' },
      { type: 'bullet', text: 'Answer their questions. That says: **“We’re willing to help you.”**' },
      { type: 'bullet', text: 'Befriend them. That says: **“You don’t have to stand alone.”**' },
      { type: 'bullet', text: 'Invite them back. That says: **“We want you here.”**' },
      { type: 'body', text: 'And none of those things require a leadership title. Any one of us can do them.' },
    ],
  },
  {
    id: 'glad-youre-here',
    slide: 4,
    section: 'Hi. I’m glad you’re here.',
    lines: [
      { type: 'body', text: 'Sometimes we overcomplicate membership. We start thinking about marketing. Social media. Recruitment campaigns. Promotional materials.' },
      { type: 'body', text: 'All of those things can help.' },
      { type: 'body', text: 'But sometimes the most powerful membership strategy is simply walking up to a guest and saying:' },
      { type: 'strong', text: '“Hi. I’m glad you’re here.”' },
      { type: 'body', text: 'That’s it.' },
    ],
  },
  {
    id: 'first-experience',
    slide: 4,
    section: 'Somebody’s chair',
    lines: [
      { type: 'body', text: 'Think about your first experience somewhere new. Maybe a restaurant you’ve never been to. Maybe a new workplace. Maybe a church. Maybe a new organization.' },
      { type: 'body', text: 'You don’t know anybody. You’re trying to figure out where to sit. You’re looking around.' },
      { type: 'body', text: 'And you’re hoping you don’t accidentally sit in somebody’s chair.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      { type: 'body', text: 'Then somebody walks up and says: “Hey! Welcome. We’re glad you’re here.”' },
      { type: 'body', text: 'Immediately, the environment changes. You relax. You feel noticed. You feel wanted. That’s the power of a first impression.' },
    ],
  },
  {
    id: 'who-we-are',
    slide: 4,
    section: 'Demonstrate who we are',
    lines: [
      { type: 'body', text: 'And remember this:' },
      { type: 'strong', text: 'A guest’s first experience is not just an opportunity to recruit a member. It’s an opportunity to demonstrate who we are.' },
      { type: 'body', text: 'If we say we’re a welcoming club… we need to actually welcome people.' },
      { type: 'body', text: 'If we say we’re supportive… we need to demonstrate support.' },
      { type: 'body', text: 'If we say we’re a community… people should feel that community when they walk through the door.' },
    ],
  },
  {
    id: 'slide-5',
    slide: 5,
    section: 'Show members that you care',
    lines: [
      { type: 'stage', text: 'ADVANCE TO SLIDE 5' },
      { type: 'strong', text: 'Show Members That You Care' },
      { type: 'body', text: 'Now we move from guests to the people who are already here. The presentation gives us six ways:' },
      { type: 'bullet', text: 'Be a mentor.' },
      { type: 'bullet', text: 'Show interest in others.' },
      { type: 'bullet', text: 'Be considerate.' },
      { type: 'bullet', text: 'Evaluate effectively.' },
      { type: 'bullet', text: 'Recognize achievements.' },
      { type: 'bullet', text: 'Foster camaraderie.' },
    ],
  },
  {
    id: 'do-i-matter',
    slide: 5,
    section: 'Do I matter here?',
    lines: [
      { type: 'body', text: 'I really like this section because it gets to the heart of what makes an organization healthy.' },
      { type: 'body', text: 'People want to know: **“Do I matter here?”**' },
      { type: 'body', text: 'Not: “How many members does the club have?” Not: “How impressive is the agenda?” Not: “How many awards did we win?”' },
      { type: 'body', text: 'Those things have value. But people want to know: **“Does anybody actually care whether I’m here?”**' },
      { type: 'body', text: 'And that’s something we can answer through our behavior.' },
    ],
  },
  {
    id: 'pay-attention',
    slide: 5,
    section: 'People don’t always announce it',
    lines: [
      { type: 'body', text: 'These aren’t complicated concepts. But they require intentionality.' },
      { type: 'body', text: 'Because people don’t always announce when they’re struggling.' },
      { type: 'body', text: 'Sometimes the person who is struggling is the person who keeps saying: “I’m fine.”' },
      { type: 'body', text: 'Sometimes the person who is losing motivation doesn’t say: “I’m thinking about leaving.” They simply stop coming.' },
      { type: 'body', text: 'That’s why we have to pay attention. Sometimes showing someone you care is as simple as:' },
      { type: 'quote', text: 'Hey, I haven’t seen you lately. Is everything okay?' },
      { type: 'quote', text: 'How did that project go?' },
      { type: 'quote', text: 'I noticed you took on that role. Great job.' },
      { type: 'body', text: 'Those small moments matter.' },
    ],
  },
  {
    id: 'evaluation',
    slide: 5,
    section: 'Evaluation is not an ambush',
    lines: [
      { type: 'stage', text: 'REMAIN ON SLIDE 5' },
      { type: 'body', text: 'And then there’s **evaluation.** Toastmasters gives us a wonderful opportunity to help people grow through evaluation.' },
      { type: 'body', text: 'But evaluation isn’t supposed to be: “Let me tell you everything you did wrong.”' },
      { type: 'body', text: 'That’s not an evaluation.' },
      { type: 'strong', text: 'That’s an ambush with a stopwatch.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      { type: 'body', text: 'Effective evaluation recognizes what worked. It identifies opportunities for improvement. And it gives the speaker something practical to work on.' },
      { type: 'body', text: 'The goal isn’t to make somebody feel bad. The goal is to make somebody better.' },
    ],
  },
  {
    id: 'other-side',
    slide: 5,
    section: 'A person on the other side',
    lines: [
      { type: 'stage', text: 'REMAIN ON SLIDE 5' },
      { type: 'body', text: 'And we should remember that when we evaluate. Because there is a person on the other side of that evaluation.' },
      { type: 'body', text: 'There’s a person who had enough courage to stand in front of this room and say: “I’m going to try.”' },
      { type: 'body', text: 'And our job is to help that person become better at trying.' },
      { type: 'bullet', text: 'Honest without being harsh.' },
      { type: 'bullet', text: 'Specific without being discouraging.' },
      { type: 'bullet', text: 'Challenge someone while still encouraging them.' },
      { type: 'body', text: 'People need accountability. But people also need encouragement. And when people know their efforts are recognized, they become more willing to participate, volunteer, take risks, and lead.' },
      { type: 'body', text: 'That’s how you build a healthy club.' },
    ],
  },
  {
    id: 'change-101',
    slide: 5,
    section: 'Change Management 101',
    lines: [
      { type: 'stage', text: 'REMAIN ON SLIDE 5' },
      { type: 'body', text: 'Now let’s connect this to our theme: **National Wellness Communication for Change.**' },
      { type: 'body', text: 'Change is difficult. We all know this. You can announce a change and somebody will immediately ask: “Why?”' },
      { type: 'body', text: 'You explain why. Then they ask: “Okay…but why?” You explain it again. Then they say: “Well, that’s not how we used to do it.”' },
      { type: 'strong', text: 'Congratulations. You’ve officially entered Change Management 101.' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
    ],
  },
  {
    id: 'listen',
    slide: 5,
    section: 'Explain why — then listen',
    lines: [
      { type: 'body', text: 'But here’s what I’ve learned: People don’t always resist change because they hate change. Sometimes they resist change because they don’t understand it.' },
      { type: 'body', text: 'That’s why communication is so important.' },
      { type: 'bullet', text: 'If we’re going to make a change, explain **why**.' },
      { type: 'bullet', text: 'Explain what is changing.' },
      { type: 'bullet', text: 'Explain how it affects people.' },
      { type: 'body', text: 'And then… **listen.** Because communication isn’t just talking. It’s listening.' },
      { type: 'body', text: 'Sometimes leadership means being willing to hear something you don’t want to hear. And that’s difficult.' },
    ],
  },
  {
    id: 'intelligent-person',
    slide: 5,
    section: 'Disagreement can be healthy',
    lines: [
      { type: 'body', text: 'Because we all love people who agree with us. You say: “I think we should do this.” They say: “Absolutely!” And you think: “What an intelligent person!”' },
      { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      { type: 'body', text: 'Then someone says: “I don’t think that’s going to work.” And suddenly you’re questioning their commitment to the organization.' },
      { type: 'body', text: 'But disagreement can be healthy. Sometimes the person challenging your idea is helping you improve it.' },
      { type: 'body', text: 'A healthy club makes room for that.' },
    ],
  },
  {
    id: 'slide-6',
    slide: 6,
    section: 'Keep your club thriving',
    lines: [
      { type: 'stage', text: 'ADVANCE TO SLIDE 6' },
      { type: 'strong', text: 'Conclusion — Keep Your Club Thriving!' },
      { type: 'body', text: 'And I want to leave you with a challenge.' },
      { type: 'body', text: 'Don’t try to change everything tomorrow. Don’t leave this meeting thinking: “We need a 47-point strategic plan!”' },
      { type: 'body', text: 'Start smaller.' },
    ],
  },
  {
    id: 'one-person',
    slide: 6,
    section: 'One person before the next meeting',
    lines: [
      { type: 'strong', text: 'Before our next meeting, intentionally improve the experience of one person.' },
      { type: 'bullet', text: 'Find somebody you don’t normally talk to.' },
      { type: 'bullet', text: 'Ask how they’re doing.' },
      { type: 'bullet', text: 'Invite them to take a role.' },
      { type: 'bullet', text: 'Give them a sincere compliment.' },
      { type: 'bullet', text: 'Offer to help. Recognize something they’ve done well. Or simply listen.' },
      { type: 'body', text: 'One person. One interaction. One opportunity to make somebody’s experience better.' },
    ],
  },
  {
    id: 'culture',
    slide: 6,
    section: 'Culture is repeated behavior',
    lines: [
      { type: 'body', text: 'Because culture isn’t created in one giant moment. Culture is created through repeated behavior.' },
      { type: 'bullet', text: 'Every conversation contributes to the climate.' },
      { type: 'bullet', text: 'Every evaluation contributes to the climate.' },
      { type: 'bullet', text: 'Every welcome contributes to the climate.' },
      { type: 'bullet', text: 'Every volunteer contributes to the climate.' },
      { type: 'bullet', text: 'Every act of support contributes to the climate.' },
    ],
  },
  {
    id: 'the-choice',
    slide: 6,
    section: 'What kind of climate will I create?',
    lines: [
      { type: 'body', text: 'So when you walk into this room, don’t just ask: **“What’s on the agenda?”**' },
      { type: 'body', text: 'Ask yourself: **“What kind of climate am I going to create tonight?”**' },
      { type: 'body', text: 'Because you have a choice.' },
      { type: 'bullet', text: 'You can add to the tension… or you can add to the encouragement.' },
      { type: 'bullet', text: 'You can close the door… or you can open one.' },
      { type: 'bullet', text: 'You can simply attend… or you can contribute.' },
    ],
  },
  {
    id: 'close',
    slide: 6,
    section: 'Not survive. THRIVE.',
    lines: [
      { type: 'body', text: 'And if each of us chooses to make this club just a little more welcoming… a little more supportive… a little more encouraging… and a little more intentional…' },
      { type: 'body', text: 'then we’re doing more than creating a successful Toastmasters club.' },
      { type: 'body', text: 'We’re creating a healthy environment where people can grow. Where leaders can develop. Where guests can become members. Where members can become mentors. Where speakers can become confident communicators.' },
      { type: 'body', text: 'And where people know: **“I belong here.”**' },
      { type: 'body', text: 'That is the kind of club climate I want us to create. Not a club where people simply survive.' },
      { type: 'strong', text: 'But a club where people THRIVE.' },
      { type: 'body', text: 'Thank you.' },
      { type: 'stage', text: 'PAUSE — SMILE — WAIT FOR APPLAUSE' },
    ],
  },
];

function hostCue(id: string, section: string, lines: CueLine[]): SpeechCue {
  return { id, slide: 0, section, lines };
}

export const MEETING_SEGMENTS: MeetingSegment[] = [
  {
    id: 'welcome',
    label: 'Welcome',
    title: 'Welcome guests and introduce the Toastmaster',
    timingPresetId: 'off',
    cues: [
      hostCue('welcome-open', 'Good evening', [
        { type: 'body', text: 'Good evening, Toastmasters, fellow members, and honored guests.' },
        { type: 'body', text: 'If you are a guest tonight, I want you to take a breath. You made it. You’re in a seat. Nobody has handed you a timer yet.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
        { type: 'body', text: 'That’s a good start.' },
        { type: 'body', text: 'My name is Larry Sharpe. My job is simple. Make sure you feel welcome. Then get Gary up here before I start making announcements I was not assigned.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      ]),
      hostCue('welcome-guests', 'Welcome of guests', [
        { type: 'body', text: 'Because I remember what this feels like. You walk in. You don’t know the language yet. You don’t know when to clap. And somebody is already saying “Table Topics” like that’s a normal thing to say in public.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
        { type: 'body', text: 'So let me translate.' },
        { type: 'strong', text: 'You are welcome here.' },
        { type: 'body', text: 'You do not have to perform tonight. You do not have to know Toastmasters. You do not have to be impressive. You just have to be present. And we are glad you are.' },
        { type: 'stage', text: 'PAUSE — look at the guests' },
      ]),
      hostCue('welcome-dignitary', 'Recognize Dr. Doreen Hamilton', [
        { type: 'body', text: 'We also have a dignitary with us tonight. And I want to say her name with the respect it deserves.' },
        { type: 'strong', text: 'Dr. Doreen Hamilton.' },
        { type: 'body', text: 'Doctor Hamilton is our guest speaker. She is working in Motivational Strategies, Level 5, from the Leadership Excellence Series: The Leader as a Coach.' },
        { type: 'body', text: 'Her speech is titled **Build, Inspire, Empower: Leading Through Coaching.**' },
        { type: 'body', text: 'Which is a gift. Because every speaker is a role model. And tonight, we get to learn from someone who came to coach us toward better leadership.' },
        { type: 'body', text: 'Dr. Hamilton, would you please stand so we can welcome you properly?' },
        { type: 'stage', text: 'LEAD APPLAUSE — wait for her to stand — then thank her and invite her to be seated' },
        { type: 'body', text: 'Thank you, Doctor. We are honored you are here. Gary will take us to your speech when the time comes. I just needed this room to know we have treasure in the house.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      ]),
      hostCue('welcome-members', 'Members, set the climate', [
        { type: 'body', text: 'Members: if there is a guest near you, that is not decoration. That is your assignment.' },
        { type: 'body', text: 'Greet them. Sit with them. Tell them they’re in the right place. Don’t let somebody sit in a room full of people and still feel alone.' },
        { type: 'body', text: 'Tonight’s theme is **National Wellness Communication for Change.** Our Word of the Day is **THRIVE.**' },
        { type: 'body', text: 'Wellness starts right here. With how we talk. With how we welcome. With whether a new person feels like they walked into a meeting… or into a club that actually wanted them.' },
      ]),
      hostCue('welcome-tmoe', 'Introduce Gary Choplin', [
        { type: 'body', text: 'And the person who will lead that climate tonight is our Toastmaster of the Evening, **Gary Choplin.**' },
        { type: 'body', text: 'Gary is going to take us through the program. He’s going to set the tone. And he’s going to do it better than I would, because if I keep talking, this welcome is going to need its own timer.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
        { type: 'body', text: 'Please help me welcome our Toastmaster of the Evening, Gary Choplin.' },
        { type: 'stage', text: 'LEAD APPLAUSE — hand Gary the floor — then be seated' },
      ]),
    ],
  },
  {
    id: 'speech',
    label: 'Speech',
    title: 'Creating the Best Club Climate',
    timingPresetId: '10-15',
    cues: SPEECH_CUES,
  },
  {
    id: 'adjourn',
    label: 'Adjourn',
    title: 'Adjourn the meeting',
    timingPresetId: 'off',
    cues: [
      hostCue('adjourn-return', 'I’m back', [
        { type: 'body', text: 'Toastmasters, guests, and friends… I’m back.' },
        { type: 'body', text: 'I told you I had two jobs tonight. Welcome you at the beginning. Let you go home at the end.' },
        { type: 'body', text: 'I am a man of my word. Which, if you’ve ever been on a committee with me, may come as breaking news.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      ]),
      hostCue('adjourn-thanks', 'Thank you', [
        { type: 'body', text: 'Thank you to Gary Choplin for leading us, keeping us on track, and politely not letting me take the meeting back in the middle.' },
        { type: 'body', text: 'And a special thank you to Dr. Doreen Hamilton. You didn’t just visit. You built. You inspired. You empowered. That’s not a guest appearance. That’s coaching.' },
        { type: 'stage', text: 'LEAD APPLAUSE' },
        { type: 'body', text: 'Thank you to everybody who took a role. Thank you to our speakers, who stood up here on purpose. Thank you to our evaluators, who had to be honest and kind in the same two minutes. That’s not evaluation. That’s a miracle.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
        { type: 'body', text: 'And thank you to our guests for staying all the way to “adjourned.” That is commitment. Or you couldn’t find your keys. Either way, we’re honored.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      ]),
      hostCue('adjourn-thrive', 'Leave them with THRIVE', [
        { type: 'body', text: 'If this room felt welcoming tonight, it wasn’t the chairs. It was you.' },
        { type: 'body', text: 'Our Word of the Day was **THRIVE.** So here is my closing thought.' },
        { type: 'body', text: 'Don’t just survive until the next meeting. Don’t just survive the parking lot. Go out and **THRIVE.**' },
        { type: 'body', text: 'And if you can’t thrive tonight… at least make it to your car without accidentally joining another conversation in the hallway.' },
        { type: 'stage', text: 'PAUSE FOR LAUGHTER' },
      ]),
      hostCue('adjourn-close', 'Adjourn', [
        { type: 'body', text: 'This meeting is adjourned.' },
        { type: 'body', text: 'That’s the sentence you’ve been waiting for. I would never deny this club wellness.' },
        { type: 'stage', text: 'SMILE — gavel if you use one' },
      ]),
    ],
  },
];

